### PR TITLE
Add outscale cloud provider

### PR DESCRIPTION
**Pull request by obeyler**
Add outscale cloud provider to the fractal demo

### CODE REVIEW

**Review by obourdon — CHANGES_REQUESTED** [review]
AFAICT, there are some checks missing to reject/fail demo creation when some unsupported Outscale features are/can be activated

**Comment by obeyler** [comment]
> AFAICT, there are some checks missing to reject/fail demo creation when some unsupported Outscale features are/can be activated

Do you mean that I should check if Outscale flag is enable ? Or in case of use of BDD RDS it should failed without try to exchange with the sq infra ? I thought (but it's only my point of view) that it could be interesting to have  no constrain on demo app to see how api react when something not possible is launched. The information returned by the cli should be revelant for an user to find why the demo failed.

**Comment by obourdon** [comment]
For the Outscale flag, it will/should indeed be tested and potentially rejected by the web rest api and there is no way to implement this on the demo script side nor CLI

For the RDS feature for instance, it is usually a good practice to prevent known to fail calls at script, CLI AND API side so as to minimize useless traffic as much as possible. However, and of course unless I did not pay enough attention to the web code this is not the case currently

Hope this makes sense

**Comment by obeyler** [comment]
I agree with you. However we are not in the CLI code but in the demo script. So I don't understand the controls you want me to add in the demo script. If it is necessary to add some, it is in the CLI or in WEB.
 
Currently, there are default behaviors in WEB like selecting AWS by default when the provider is unknown. I think it would be better to return an error that the provider is unknown. After this example, I'd like to know if the control is also done at the CLI level, which makes it dependent on the evolution, or if we consider that we keep the control of the commands (the syntax of the commands) on the CLI, but that we leave the control of the validity of the parameters to WEB, so that we only have one place to maintain it.

**Review by obourdon — APPROVED** [review]

**Review by SwannCroiset — APPROVED** [review]

**Pull request merged**
